# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/gitE0Z9"

[social.params]
icon = "brand-github"

[[social]]
identifier = "medium"
name = "Medium"
url = "https://medium.com/@acrocanthosaurus627"

[social.params]
icon = "brand-medium"
